### PR TITLE
CAL-1271 : User can search events using special characters

### PR DESCRIPTION
**Pull request by seifeddineDaoud**

### CODE REVIEW

**Comment by seifeddineDaoud** [comment]
I just tested on http://plfenteap-5.1.x-snapshot-oracle.acceptance7.exoplatform.org, the error message is displayed.

**Comment by seifeddineDaoud** [comment]
when I delete addValidator(SpecialCharacterValidator.class) , the message does not appear anymore

**Comment by thomasdelhomenie** [comment]
Yes, I didn't say your fix does not allow to remove the message, I said that now the message is not displayed anymore but the event does not appear in the list of results. If I search for "test&integration" and there is an event called "test&integration", it should appear in the list of results. Do you reproduce the same behavior ?

**Comment by seifeddineDaoud** [comment]
yes, you're right. I'll correct it .

**Pull request merged**
